name: "Close stale issues"
on:
  # For debugging: toggle action by starring/unstarring the repo
  watch:
    types: [started]
  # Regular scheduling, run daily at 6AM Mountain time (12:00pm UTC)
  schedule:
  - cron: "0 12 * * *"

# See https://github.com/actions/stale/blob/master/action.yml for information on actions 
# that GitHub knows for stale issues.

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # Number of days of inactivity before marking an issue or PR stale
        days-before-stale: 1
        # Number of days of inactivity after marking stale before closing the issue or PR
        days-before-close: 1
        # Message for marking issues and PR's.
        stale-issue-message: >
          This issue has been marked as STALE due to inactivity for XX days. 
          It will be closed in YY days unless the flag is cleared.
          
          Please post a comment and remove the STALE FLAG to prevent auto-closure
          of this issue.
        #description: 'The maximum number of operations per run, used to control rate limiting.
        operations-per-run: 25
        stale-pr-message: 'This PR has been marked as STALE due to inactivity for XX days. It will be closed in YY days unless the flag is cleared.'
        # 'STALE' label to use.
        stale-issue-label: 'Inactive Issue / Stale'
        stale-pr-label: 'Inactive PR / Stale'
        # Flags that exempt issues and PRs from this check.
        exempt-issue-labels: 'Needs Review,Prioritized,Bug'
        exempt-pr-labels: 'Needs Review,Work in Progress,Prioritized'
        # Remove stale labels from issues when they are updated or commented on.
        #remove-stale-when-updated: true



